<?php

include_once(__DIR__ . '/vendor/autoload.php');

define('INDEX', '');
define('VIEWS_PATH', __DIR__ . DIRECTORY_SEPARATOR . 'views' . DIRECTORY_SEPARATOR);
define('VIEWS_INCLUDES_PATH', __DIR__ . DIRECTORY_SEPARATOR . 'views' . DIRECTORY_SEPARATOR . 'includes' .  DIRECTORY_SEPARATOR);
define('JS_PATH', INDEX . DIRECTORY_SEPARATOR . 'assets' . DIRECTORY_SEPARATOR . 'js' . DIRECTORY_SEPARATOR);
define('CSS_PATH', INDEX . DIRECTORY_SEPARATOR . 'assets' . DIRECTORY_SEPARATOR . 'css' . DIRECTORY_SEPARATOR);

?>