CREATE DATABASE IF NOT EXISTS omni;
USE omni;

DROP TABLE IF EXISTS usuario_conta;
CREATE TABLE IF NOT EXISTS usuario_conta(
	ID_USUARIO_CONTA INT UNSIGNED AUTO_INCREMENT NOT NULL,
    EMAIL VARCHAR(80) NOT NULL,
    SENHA CHAR(32) NOT NULL,
    DT_CADASTRO DATETIME DEFAULT CURRENT_TIMESTAMP,
    DT_UPDATE DATETIME,    
    PRIMARY KEY(ID_USUARIO_CONTA)    
)ENGINE = InnoDB DEFAULT CHARSET = Latin1;

DROP TABLE IF EXISTS usuario;
CREATE TABLE IF NOT EXISTS usuario(
	ID_USUARIO INT UNSIGNED AUTO_INCREMENT NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(80) NOT NULL,
    SEXO CHAR(1) NOT NULL,
    DT_NASCIMENTO DATETIME,
    DT_CADASTRO DATETIME DEFAULT CURRENT_TIMESTAMP,
    DT_UPDATE DATETIME,
    ID_USUARIO_CONTA INT UNSIGNED NOT NULL,
    PRIMARY KEY(ID_USUARIO),
    CONSTRAINT USUARIO_CONTA_USUARIO 
	FOREIGN KEY (ID_USUARIO_CONTA) 
	REFERENCES usuario_conta (ID_USUARIO_CONTA) 
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
)ENGINE = InnoDB DEFAULT CHARSET = Latin1;

SELECT * FROM usuario;
SELECT * FROM usuario_conta;