CREATE DATABASE IF NOT EXISTS omni;
USE omni;

DROP TABLE IF EXISTS usuario;
CREATE TABLE IF NOT EXISTS usuario(
	ID_USUARIO INT UNSIGNED AUTO_INCREMENT NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(80) NOT NULL,
    SEXO CHAR(1) NOT NULL,
    DT_NASCIMENTO DATETIME,
    DT_CADASTRO DATETIME DEFAULT CURRENT_TIMESTAMP,
    DT_UPDATE DATETIME,
    PRIMARY KEY(ID_USUARIO)    
)ENGINE = InnoDB DEFAULT CHARSET = Latin1;

SELECT * FROM usuario;